version: '3.9'

services:
  app:
    depends_on:
      - db
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgre-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  proxy:
    depends_on:
      - app
    build:
      context: ./proxy
    restart: always
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static

volumes:
  postgre-data:
  static-data:
