name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker-compose -f docker-compose.yml run --rm app sh -c 'python manage.py wait_for_db && python manage.py test'
      - name: Lint
        run: npm run lint
