name: Develop environment deployment

on:
  push:
    branches:
      - "dev"

jobs:
  vps-pull:
    name: VPS pulls and run Docker container
    runs-on: ubuntu-20.04
    steps:
      - name: Connect to VPS
        env:
          VPS_SOURCE_DIR: ${{ secrets.VPS_SOURCE_DIR }}
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: "${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PORT }}"
          privateKey: ${{ secrets.VPS_PRIVATE_KEY }}
          debug: false
          command: |
            cd ./${{ env.VPS_SOURCE_DIR }}
            git pull origin dev
            docker-compose -f docker-compose-deploy.yml up -d && \
            mdkir .ssl && \
            touch .ssl/${{ secrets.SSL_FILE_NAME }} && \
            ${{ secrets.SSL_FILE_CONTENT }} > ${{ secrets.SSL_FILE_NAME }} && \
            docker cp .ssl/${{ secrets.SSL_FILE_NAME }} rest-api-django-learning_proxy_1:/vol/static

