name: Develop environment deployment

on:
  push:
    branches:
      - "dev"

jobs:
  vps-pull:
    name: VPS pulls and run Docker container
    runs-on: ubuntu-20.04
    steps:
      - name: Connect to VPS
        env:
          VPS_SOURCE_DIR: ${{ secrets.VPS_SOURCE_DIR }}
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.VPS_USERNAME }}:${{ secrets.VPS_HOST }}:${{ secrets.PORT }}
          privateKey: ${{ VPS_PRIVATE_KEY }}
          debug: false
          command: ls -a
