name: Develop environment deployment

on:
  push:
    branches:
      - "dev"

jobs:
  vps-pull:
    name: VPS pulls and run Docker container
    runs-on: ubuntu-20.04
    steps:
      - name: Connect to VPS
        env:
          VPS_SOURCE_DIR: ${{ secrets.VPS_SOURCE_DIR }}
          SSL_DIR: .ssl
          SSL_FILE_PATH: .ssl/${{ secrets.SSL_FILE_NAME }}
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: "${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PORT }}"
          privateKey: ${{ secrets.VPS_PRIVATE_KEY }}
          debug: false
          command: |
            cd ./${{ env.VPS_SOURCE_DIR }}
            git pull origin dev
            docker-compose -f docker-compose-deploy.yml build
            docker-compose -f docker-compose-deploy.yml up -d
            mkdir -p ${{ env.SSL_DIR }}
            touch ${{ env.SSL_FILE_PATH }}
            > ${{ env.SSL_FILE_PATH }} cat <<< ${{ secrets.SSL_FILE_CONTENT }}
            docker exec -ti rest-api-django-learning_app_1 rm -r /vol/web/.ssl/
            docker cp ${{ env.SSL_FILE_PATH }} rest-api-django-learning_app_1:/vol/web/.ssl
            echo "===== Success running dev deployment ====="
