name: Develop environment deployment

on:
  push:
    branches:
      - "dev"

jobs:
  vps-pull:
    name: VPS pulls and run Docker container
    runs-on: ubuntu-20.04
    steps:
      - name: Connect to VPS
        env:
          VPS_HOST: ${{ secrets.HOST }}
          VPS_USERNAME: ${{ secrets.USERNAME }}
          VPS_PASSWORD: ${{ secrets.PASSWORD }}
          VPS_PORT: ${{ secrets.PORT }}
          SOURCE_DIR: ${{ secrets.SOURCE_DIR }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: $VPS_HOST
          username: $VPS_USERNAME
          password: $VPS_PASSWORD
          port: ${{ secrets.PORT }}
          script: |
            cd "./$SOURCE_DIR"
            git pull
            docker-compose -f docker-compose-deploy.yml up -d
