name: Develop environment deployment

on:
  push:
    branches:
      - "dev"

jobs:
  vps-pull:
    name: VPS pulls and run Docker container
    runs-on: ubuntu-20.04
    steps:
      - name: Connect to VPS
        env:
          VPS_SOURCE_DIR: ${{ secrets.VPS_SOURCE_DIR }}
          SSL_DIR: .ssl
          SSL_FILE_PATH: .ssl/${{ secrets.SSL_FILE_NAME }}
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: "${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PORT }}"
          privateKey: ${{ secrets.VPS_PRIVATE_KEY }}
          debug: false
          command: |
            cd ./${{ env.VPS_SOURCE_DIR }}
            git checkout dev
            git pull
            rm .env
            touch .env
            <<EOF>> .env cat
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
            DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}
            EOF
            docker-compose -f docker-compose-dev-deploy.yml build
            docker-compose -f docker-compose-dev-deploy.yml up -d
            echo "===== Success running dev deployment ====="
