name: Develop environment deployment

on:
  push:
    branches:
      - "dev"

jobs:
  vps-pull:
    name: VPS pulls and run Docker container
    runs-on: ubuntu-20.04
    steps:
      - name: Connect to VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
          VPS_SOURCE_DIR: ${{ secrets.VPS_SOURCE_DIR }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: $VPS_HOST
          username: $VPS_USERNAME
          password: $VPS_PASSWORD
          port: ${{ secrets.PORT }}
          script: whoami
